[build]
  command = "cd app && npm ci && npm run build"
  publish = "app/dist"

[build.environment]
  NODE_VERSION = "22"
  VITE_API_URL = "https://appingles-km24.onrender.com/api"
  VITE_AUTH_MODE = "firebase"
  VITE_FIREBASE_API_KEY = "AIzaSyAfcQfLkf-ZuugTjtEjvvhsWg6kbmwuG6U"
  VITE_FIREBASE_AUTH_DOMAIN = "appingles-app.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "appingles-app"
  VITE_FIREBASE_STORAGE_BUCKET = "appingles-app.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "231095268664"
  VITE_FIREBASE_APP_ID = "1:231095268664:web:3f2e705bd1b16ce937bdcd"
  VITE_FIREBASE_MEASUREMENT_ID = "G-GS0296HSFK"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
